### ISSUE TITLE
使用WirePusher，消息显示的发送者是错误的

### ISSUE THREAD

**Issue by ballyhuang** [IlineI/WeChatPush#16]
你好，我是使用WirePusher接收微信消息，但是群聊的消息显示的发送者是错误的。如我附的图，都是热考无忧，无法识别是谁发的消息。其他的群聊也是如此。
![Screenshot_20220815-150725_WirePusher](https://user-images.githubusercontent.com/31944828/184591797-9ec2d657-7fe4-47b1-ab64-d78b674a84c7.png)
#

**Comment by chase535** [comment]
已找到问题所在，正在积极修复

**Comment by chase535** [comment]
已修复、合并。但itchat中有一个issue：[关于群消息包中ActualNickName的获取](https://github.com/littlecodersh/ItChat/issues/522)，由于我的微信不用群聊，所以无法验证此issue现在是否还会出现。现在可以close了，如果获取不了昵称再open就行。

**Comment by IlineI** [comment]
OK

**Comment by IlineI** [comment]
谢谢@chase535
