### ISSUE TITLE
使用WirePusher，消息显示的发送者现在变没有了

### ISSUE THREAD

**Issue by ballyhuang** [IlineI/WeChatPush#17]
现在变成只有消息，没有昵称了。选项里普通消息与通话邀请都是选择3，谢谢！
![Screenshot_20220815-221232_WirePusher](https://user-images.githubusercontent.com/31944828/184652241-f63d850b-cb9e-4a1e-b306-4fcaef17cb0c.png)

**Comment by chase535** [comment]
已紧急修复，但还未合并，[点此进入分支](https://github.com/chase535/WeChatPush)

**Comment by ballyhuang** [comment]
> 已经紧急修复，但需要合并，[点此进入分支](https://github.com/chase535/WeChatPush)

分支的群消息可以正常了，谢谢！
